project_id = "rowcloxlszwnowlggqon"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[db]
port = 54322

[edge_runtime]
enabled = true

[functions.google-adsense]
verify_jwt = true

[functions.google-analytics]
verify_jwt = true

[functions.google-search-console]
verify_jwt = true

[functions.google-oauth]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[storage]
enabled = true
file_size_limit = "50MiB"

[auth.email]
enable_signup = true
enable_confirmations = false